/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.QueryProvide;
import Data.Provider;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author POLANCO
 */
public class AddProvider extends javax.swing.JDialog {
     private javax.swing.table.DefaultTableModel modelProvider;
    /**
     * Creates new form AddProvider
     */
    public AddProvider(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboSearchProvider = new javax.swing.JComboBox<>();
        jTextParameter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProvider = new javax.swing.JTable();
        jButtonAddProvider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ComboSearchProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT o C.C", "Razon social" }));

        jTextParameter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextParameterKeyTyped(evt);
            }
        });

        jTableProvider.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NIT o C.C", "Razon Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableProvider);

        jButtonAddProvider.setText("Agregar");
        jButtonAddProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProviderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboSearchProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddProvider)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboSearchProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonAddProvider)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextParameterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextParameterKeyTyped
        modelProvider = new javax.swing.table.DefaultTableModel();
        jTableProvider.setModel(modelProvider);
        modelProvider.addColumn("Codigo");
        modelProvider.addColumn("Nombre");
        modelProvider.addColumn("Descripción");
        modelProvider.addColumn("Unidad de medida");
        modelProvider.addColumn("Unidades");
        String aux = ComboSearchProvider.getSelectedItem().toString();
        String attribute = new String(aux);
        QueryProvide qp = new QueryProvide();
        try {
            java.sql.ResultSet rsp = qp.getProvideForWhere(attribute, jTextParameter.getText());
            int quantityRow = qp.getCantProvide();
            while (rsp.next()) {
                Object[] rowModel = new Object[quantityRow];
                for (int i = 0; i < quantityRow; i++) {
                    rowModel[i] = rsp.getObject(i + 1);
                }
                modelProvider.addRow(rowModel);
            }
        } catch (SQLException e) {
            System.err.print(e);
        }
        qp.closeConnection();
        
    }//GEN-LAST:event_jTextParameterKeyTyped

    private void jButtonAddProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProviderActionPerformed
        int selectedRow = this.jTableProvider.getSelectedRow();
        if(selectedRow>=0){
            HomeUser.getjTextNITCC().setText(modelProvider.getValueAt(selectedRow, 0).toString());
            HomeUser.getjTextNameProvider().setText(modelProvider.getValueAt(selectedRow, 1).toString());
        }
        else{
            JOptionPane.showMessageDialog(this,"Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jButtonAddProviderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProvider dialog = new AddProvider(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSearchProvider;
    private javax.swing.JButton jButtonAddProvider;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProvider;
    private javax.swing.JTextField jTextParameter;
    // End of variables declaration//GEN-END:variables
}
