/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.QueryClient;
import BusinessLogic.QueryProduct;
import BusinessLogic.QueryBill;
import BusinessLogic.QueryBillProduct;
import Data.Bill;
import Data.BillProduct;
import Data.Client;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author POLANCO
 */
public class HomeUser extends javax.swing.JFrame {

    private AddProduct frmAddProduct;
    private javax.swing.table.DefaultTableModel modelDetal;
    private String user;

    /**
     * Creates new form HomeUser
     */
    public HomeUser() {
        initComponents();
        this.jPanelInsertClient.setVisible(false);
        this.jPanel6.setVisible(false);
        frmAddProduct = new AddProduct(this, false);

    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }
    
    
    
    private class TableModel extends DefaultTableModel {

        private final boolean[] tableColums = {false, false, false, false, false, false};

        @Override
        public final boolean isCellEditable(int row, int column) {
            return this.tableColums[column];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupClient = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jCbSearchProFrmUser = new javax.swing.JComboBox<>();
        jTextSearchProFrmUser = new javax.swing.JTextField();
        jbtSearchProFrmUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelInsertClient = new javax.swing.JPanel();
        jTextLLastName = new javax.swing.JTextField();
        jTextEmailClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIdClient = new javax.swing.JTextField();
        jTextNameClient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnInsertCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFLastName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextPhoneClient = new javax.swing.JTextField();
        jRadioButtonNewClient = new javax.swing.JRadioButton();
        jRadioButtonOldClient = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextClientSelected = new javax.swing.JTextField();
        jPanelDetalles = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDetalle = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDetal = new javax.swing.JTable();
        jButtonFrmAddProduct = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jCBSearchClient = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jButtonCheckIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jCbSearchProFrmUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre" }));

        jbtSearchProFrmUser.setText("Buscar");
        jbtSearchProFrmUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchProFrmUserActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar");

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        jTable2.setModel(model);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Precio");
        model.addColumn("Unidad de medida");
        model.addColumn("Cantidad");

        QueryProduct qp = new QueryProduct();
        try{
            java.sql.ResultSet rsp = qp.getProducts();
            int quantityRow = qp.getCantProduct();
            while(rsp.next()){
                Object [] rowModel = new Object[quantityRow];
                for(int i=0; i<quantityRow; i++){
                    rowModel[i] = rsp.getObject(i+1);
                }
                model.addRow(rowModel);
            }
        }catch(SQLException e){
            System.err.print(e);
        }
        qp.closeConnection();
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCbSearchProFrmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jTextSearchProFrmUser)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSearchProFrmUser)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbSearchProFrmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSearchProFrmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearchProFrmUser))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/GUI/box.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Entradas", jPanel4);

        jPanelInsertClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Cliente"));

        jLabel7.setText("Correo");

        jLabel6.setText("Telefono del cliente *");

        jLabel2.setText("Numero de documento *");

        jLabel4.setText("Nombre del cliente *");

        jbtnInsertCliente.setText("Registrar");
        jbtnInsertCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertClienteActionPerformed(evt);
            }
        });

        jLabel9.setText("Primer apellido *");

        jLabel10.setText("Segundo apellido");

        javax.swing.GroupLayout jPanelInsertClientLayout = new javax.swing.GroupLayout(jPanelInsertClient);
        jPanelInsertClient.setLayout(jPanelInsertClientLayout);
        jPanelInsertClientLayout.setHorizontalGroup(
            jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertClientLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextEmailClient)))
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNameClient, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jTextIdClient)
                            .addComponent(jTextFLastName))
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jbtnInsertCliente))
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPhoneClient)))))
                .addContainerGap())
        );
        jPanelInsertClientLayout.setVerticalGroup(
            jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnInsertCliente)
                .addGap(594, 594, 594))
        );

        buttonGroupClient.add(jRadioButtonNewClient);
        jRadioButtonNewClient.setText("Cliente nuevo");
        jRadioButtonNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNewClientActionPerformed(evt);
            }
        });

        buttonGroupClient.add(jRadioButtonOldClient);
        jRadioButtonOldClient.setText("Cliente registrado");
        jRadioButtonOldClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOldClientActionPerformed(evt);
            }
        });

        jLabel11.setText("Cliente");

        jTextClientSelected.setEditable(false);

        jPanelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de productos"));

        jTableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Precio", "Unidad de medida", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableDetalle);

        modelDetal = new javax.swing.table.DefaultTableModel();
        jTableDetal.setModel(modelDetal);
        modelDetal.addColumn("Codigo");
        modelDetal.addColumn("Nomnbre");
        modelDetal.addColumn("Descripcion");
        modelDetal.addColumn("Precio");
        modelDetal.addColumn("Unidad de medida");
        modelDetal.addColumn("Cantidad");
        jScrollPane4.setViewportView(jTableDetal);

        jButtonFrmAddProduct.setText("Agregar productos");
        jButtonFrmAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrmAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDetallesLayout = new javax.swing.GroupLayout(jPanelDetalles);
        jPanelDetalles.setLayout(jPanelDetallesLayout);
        jPanelDetallesLayout.setHorizontalGroup(
            jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesLayout.createSequentialGroup()
                .addGroup(jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetallesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDetallesLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFrmAddProduct)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelDetallesLayout.setVerticalGroup(
            jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFrmAddProduct)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));

        jCBSearchClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documento", "Nombre y apellido" }));
        jCBSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSearchClientActionPerformed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Primer apellido", "Segundo apellido", "Telefono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClient);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jCBSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jButtonCheckIn.setText("Facturar");
        jButtonCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextClientSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonNewClient)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButtonOldClient)
                        .addGap(0, 483, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelInsertClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButtonCheckIn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNewClient)
                    .addComponent(jRadioButtonOldClient))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextClientSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jPanelInsertClient, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonCheckIn)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Salidas", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Operaciones", new javax.swing.ImageIcon(getClass().getResource("/GUI/icono-eficencia.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static JTable getjTableDetal() {
        return jTableDetal;
    }

    private boolean checkMail(String mail) {
        String emailPattern = "^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@"
                + "[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4})$";
        Pattern pattern = Pattern.compile(emailPattern);
        String email = mail;
        boolean valide = false;
        if (mail != null) {
            Matcher matcher = pattern.matcher(email);
            if (matcher.matches()) {
                valide = true;
            }
        }
        return valide;
    }

    private void jbtSearchProFrmUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchProFrmUserActionPerformed
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();

        jTable2.setModel(model);
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Precio");
        model.addColumn("Unidad de medida");
        model.addColumn("Cantidad");
        QueryProduct qpw = new QueryProduct();
        ResultSet rsw = null;
        if (!jTextSearchProFrmUser.getText().equals("")) {
            rsw = qpw.getProductForWhere(jCbSearchProFrmUser.getSelectedItem().toString(), jTextSearchProFrmUser.getText());
            int size = qpw.getCantProduct();
            try {
                while (rsw.next()) {
                    Object[] rowModel = new Object[size];
                    for (int i = 0; i < size; i++) {
                        rowModel[i] = rsw.getObject(i + 1);
                    }
                    model.addRow(rowModel);
                }
            } catch (SQLException e) {
                System.err.print(e);
            }
        } else {
            if (jTextSearchProFrmUser.getText().equals("")) {
                try {
                    java.sql.ResultSet rsp = qpw.getProducts();
                    int quantityRow = qpw.getCantProduct();
                    while (rsp.next()) {
                        Object[] rowModel = new Object[quantityRow];
                        for (int i = 0; i < quantityRow; i++) {
                            rowModel[i] = rsp.getObject(i + 1);
                        }
                        model.addRow(rowModel);
                    }
                } catch (SQLException e) {
                    System.err.print(e);
                }

            }
        }

        qpw.closeConnection();
    }//GEN-LAST:event_jbtSearchProFrmUserActionPerformed

    private void jRadioButtonNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNewClientActionPerformed
        this.jPanelInsertClient.setVisible(true);
        this.jPanel6.setVisible(false);
    }//GEN-LAST:event_jRadioButtonNewClientActionPerformed

    private void jRadioButtonOldClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOldClientActionPerformed
        this.jPanelInsertClient.setVisible(false);
        this.jPanel6.setVisible(true);
    }//GEN-LAST:event_jRadioButtonOldClientActionPerformed

    private void jbtnInsertClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertClienteActionPerformed
        QueryClient qp = new QueryClient();
        Client client = new Client();
        if (!jTextIdClient.getText().equals("") && !jTextNameClient.getText().equals("") && !jTextFLastName.getText().equals("")) {
            if (!jTextEmailClient.getText().equals("")) {
                boolean aux = checkMail(jTextEmailClient.getText());
                if (aux) {
                    client.setDocument(jTextIdClient.getText());
                    client.setName(jTextNameClient.getText());
                    client.setFirstLastName(jTextFLastName.getText());
                    client.setLastLastName(jTextLLastName.getText());
                    client.setPhone(jTextPhoneClient.getText());
                    client.setEmail(jTextEmailClient.getText());

                    if (qp.insertClient(client)) {
                        JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");
                        jTextClientSelected.setText(jTextIdClient.getText());
                        jTextIdClient.setText("");
                        jTextNameClient.setText("");
                        jTextFLastName.setText("");
                        jTextLLastName.setText("");
                        jTextPhoneClient.setText("");
                        jTextEmailClient.setText("");
                        jPanelInsertClient.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas al registrar el cliente");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Correo invalido");
                }
            } else {
                if (jTextEmailClient.getText().equals("")) {
                    client.setDocument(jTextIdClient.getText());
                    client.setName(jTextNameClient.getText());
                    client.setFirstLastName(jTextFLastName.getText());
                    client.setLastLastName(jTextLLastName.getText());
                    client.setPhone(jTextPhoneClient.getText());
                    client.setEmail(jTextEmailClient.getText());

                    if (qp.insertClient(client)) {
                        JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");
                        jTextClientSelected.setText(jTextIdClient.getText());
                        jTextIdClient.setText("");
                        jTextNameClient.setText("");
                        jTextFLastName.setText("");
                        jTextLLastName.setText("");
                        jTextPhoneClient.setText("");
                        jTextEmailClient.setText("");
                        jPanelInsertClient.setVisible(false);

                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas al registrar el cliente");
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Campos requeridos se enuentran vacios");
        }
    }//GEN-LAST:event_jbtnInsertClienteActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        TableModel model = new TableModel();
        jTableClient.setModel(model);
        model.addColumn("Documento");
        model.addColumn("Nombre");
        model.addColumn("Primer apellido");
        model.addColumn("Segundo apellido");
        model.addColumn("Telefono");
        model.addColumn("Correo");
        String aux = jCBSearchClient.getSelectedItem().toString();
        String attribute = new String(aux);
        QueryClient qc = new QueryClient();
        try {
            java.sql.ResultSet rsc = qc.getClientForWhere(attribute, jTextField5.getText());
            int quantityRow = qc.getCantClient();
            while (rsc.next()) {
                Object[] rowModel = new Object[quantityRow];
                for (int i = 0; i < quantityRow; i++) {
                    rowModel[i] = rsc.getObject(i + 1);
                }
                //jCBSearchClient.get
                model.addRow(rowModel);
            }
        } catch (SQLException e) {
            System.err.print(e);
        }
        qc.closeConnection();
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jCBSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSearchClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSearchClientActionPerformed

    private void jButtonFrmAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrmAddProductActionPerformed
        frmAddProduct.setVisible(true);

    }//GEN-LAST:event_jButtonFrmAddProductActionPerformed

    private void jTableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientMouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTableClient.getSelectedRow();
            jTextClientSelected.setText(jTableClient.getValueAt(row, 0).toString());
            jPanel6.setVisible(false);
        }
    }//GEN-LAST:event_jTableClientMouseClicked

    private void jButtonCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInActionPerformed
        QueryBill Qbill = new QueryBill();
        Bill bill = new Bill();
        int j=0;
        bill.setClient(this.jTextClientSelected.getText());
        bill.setUser(user);
        /*if(Qbill.insertBill(bill)){
           /* int row = this.modelDetal.getRowCount();
            String [] element = new String[row];
            String aux = new String();
            for(int i=0;i<row;i++){
                //Problema no se de donde
                aux = modelDetal.getValueAt(i, 0).toString();
                element[i] = aux;
            }*/
            int lastBill=0;
            lastBill = Qbill.getLastIdBill();
            System.out.println(lastBill);
            /*QueryBillProduct qbp = new QueryBillProduct();
            BillProduct bp = new BillProduct();
            bp.setNBill(lastBill);
            */
            /*for(j=0;j<row;j++){
                bp.setIdProduct(element[j]);
                qbp.insertBillProduc(bp);
            }
            if(j==row-1){
                JOptionPane.showMessageDialog(this, "Se ha facturado correctamente");
            }
        }*/
    }//GEN-LAST:event_jButtonCheckInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupClient;
    private javax.swing.JButton jButtonCheckIn;
    private javax.swing.JButton jButtonFrmAddProduct;
    private javax.swing.JComboBox<String> jCBSearchClient;
    private javax.swing.JComboBox<String> jCbSearchProFrmUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelInsertClient;
    private javax.swing.JRadioButton jRadioButtonNewClient;
    private javax.swing.JRadioButton jRadioButtonOldClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableClient;
    private static javax.swing.JTable jTableDetal;
    private javax.swing.JTable jTableDetalle;
    private javax.swing.JTextField jTextClientSelected;
    private javax.swing.JTextField jTextEmailClient;
    private javax.swing.JTextField jTextFLastName;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextIdClient;
    private javax.swing.JTextField jTextLLastName;
    private javax.swing.JTextField jTextNameClient;
    private javax.swing.JTextField jTextPhoneClient;
    private javax.swing.JTextField jTextSearchProFrmUser;
    private javax.swing.JButton jbtSearchProFrmUser;
    private javax.swing.JButton jbtnInsertCliente;
    // End of variables declaration//GEN-END:variables
}
