/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.QueryClient;
import BusinessLogic.QueryProduct;
import BusinessLogic.QueryBill;
import BusinessLogic.QueryBillProduct;
import BusinessLogic.QueryCheckInProduct;
import BusinessLogic.QueryPettyCash;
import BusinessLogic.QueryProviderProduct;
import BusinessLogic.QueryUser;
import Data.Bill;
import Data.BillProduct;
import Data.CheckInProduct;
import Data.Client;
import Data.PettyCash;
import Data.ProviderProduct;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.EventListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author POLANCO
 */
public class HomeUser extends javax.swing.JFrame implements Printable {

    private AddProduct frmAddProduct;
    private javax.swing.table.DefaultTableModel modelDetal;
    private static javax.swing.table.DefaultTableModel modelProductIn;
    private String user;
    private int subtotal = 0;
    private GenerateCheckIn generatedCheckIn = new GenerateCheckIn();

    /**
     * Creates new form HomeUser
     */
    public HomeUser() {
        initComponents();
        this.jPanelInsertClient.setVisible(false);
        this.jPanel6.setVisible(false);
        frmAddProduct = new AddProduct(this, false);

    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public static JTable getjTableAddProductIn() {
        return jTableAddProductIn;
    }

    public static void setjTableAddProductIn(JTable jTableAddProductIn) {
        HomeUser.jTableAddProductIn = jTableAddProductIn;
    }

    public static JTextField getjTextNITCC() {
        return jTextNITCC;
    }

    public static void setjTextNITCC(JTextField jTextNITCC) {
        HomeUser.jTextNITCC = jTextNITCC;
    }

    public static JTextField getjTextNameProvider() {
        return jTextNameProvider;
    }

    public static void setjTextNameProvider(JTextField jTextNameProvider) {
        HomeUser.jTextNameProvider = jTextNameProvider;
    }

    public static DefaultTableModel getModelProductIn() {
        return modelProductIn;
    }

    public static void setModelProductIn(DefaultTableModel modelProductIn) {
        HomeUser.modelProductIn = modelProductIn;
    }

    @Override
    public int print(Graphics grphcs, PageFormat pf, int i) throws PrinterException {

        int cantProduct = modelDetal.getRowCount();
        generatedCheckIn.setjTextClient(jTextClientSelected);
        generatedCheckIn.setjTextSubTotal(jTextSubTotal);
        generatedCheckIn.setjTextTotal(jTextTotal);
        generatedCheckIn.setjTextIVA(jTextIVA);
        Object[] item = new Object[4];
        for (int a = 0; a < cantProduct; a++) {
            item[0] = modelDetal.getValueAt(a, 5);
            item[1] = modelDetal.getValueAt(a, 1);
            item[2] = "por ahora";
            item[3] = "Otro por ahora";
            generatedCheckIn.getModelCheckIn().addRow(item);
        }

        if (i > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D grphCheckIn = (Graphics2D) grphcs;
        grphCheckIn.translate(pf.getImageableX() + 10, pf.getImageableY() + 10);
        grphCheckIn.scale(1.0, 1.0);
        generatedCheckIn.printAll(grphcs);
        return PAGE_EXISTS;
    }

    private class TableModel extends DefaultTableModel {

        private final boolean[] tableColums = {false, false, false, false, false, false};

        @Override
        public final boolean isCellEditable(int row, int column) {
            return this.tableColums[column];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupClient = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jCbSearchProFrmUser = new javax.swing.JComboBox<>();
        jTextSearchProFrmUser = new javax.swing.JTextField();
        jbtSearchProFrmUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanelInsertClient = new javax.swing.JPanel();
        jTextLLastName = new javax.swing.JTextField();
        jTextEmailClient = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextIdClient = new javax.swing.JTextField();
        jTextNameClient = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jbtnInsertCliente = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFLastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextPhoneClient = new javax.swing.JTextField();
        jRadioButtonNewClient = new javax.swing.JRadioButton();
        jRadioButtonOldClient = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextClientSelected = new javax.swing.JTextField();
        jPanelDetalles = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDetal = new javax.swing.JTable();
        jButtonFrmAddProduct = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jCBSearchClient = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jButtonCheckIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextSubTotal = new javax.swing.JTextField();
        jTextIVA = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextNITCC = new javax.swing.JTextField();
        jTextNameProvider = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonFrmAddProvider = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableAddProductIn = new javax.swing.JTable();
        jButtonFrmAddProductIn = new javax.swing.JButton();
        jButtonInsertIn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextCash = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextReason = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPasswordOld = new javax.swing.JPasswordField();
        jPasswordNew = new javax.swing.JPasswordField();
        jPasswordConfirm = new javax.swing.JPasswordField();
        jButtonSaveChangePass = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCbSearchProFrmUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre" }));

        jbtSearchProFrmUser.setText("Buscar");
        jbtSearchProFrmUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchProFrmUserActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar");

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        jTable2.setModel(model);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Precio");
        model.addColumn("Unidad de medida");
        model.addColumn("Cantidad");

        QueryProduct qp = new QueryProduct();
        try{
            java.sql.ResultSet rsp = qp.getProducts();
            int quantityRow = qp.getCantProduct();
            while(rsp.next()){
                Object [] rowModel = new Object[quantityRow];
                for(int i=0; i<quantityRow; i++){
                    rowModel[i] = rsp.getObject(i+1);
                }
                model.addRow(rowModel);
            }
        }catch(SQLException e){
            System.err.print(e);
        }
        qp.closeConnection();
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCbSearchProFrmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jTextSearchProFrmUser)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSearchProFrmUser)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbSearchProFrmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSearchProFrmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearchProFrmUser))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/Images/box.png")), jPanel1); // NOI18N

        jPanelInsertClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Cliente"));

        jLabel13.setText("Correo");

        jLabel14.setText("Telefono del cliente *");

        jLabel5.setText("Numero de documento *");

        jLabel15.setText("Nombre del cliente *");

        jbtnInsertCliente.setText("Registrar");
        jbtnInsertCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertClientejbtnInsertClienteActionPerformed(evt);
            }
        });

        jLabel16.setText("Primer apellido *");

        jLabel17.setText("Segundo apellido");

        javax.swing.GroupLayout jPanelInsertClientLayout = new javax.swing.GroupLayout(jPanelInsertClient);
        jPanelInsertClient.setLayout(jPanelInsertClientLayout);
        jPanelInsertClientLayout.setHorizontalGroup(
            jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertClientLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jTextEmailClient)))
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNameClient, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jTextIdClient)
                            .addComponent(jTextFLastName))
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jbtnInsertCliente))
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17))
                            .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPhoneClient)))))
                .addContainerGap())
        );
        jPanelInsertClientLayout.setVerticalGroup(
            jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanelInsertClientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInsertClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnInsertCliente)
                .addGap(594, 594, 594))
        );

        jRadioButtonNewClient.setText("Cliente nuevo");
        jRadioButtonNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNewClientActionPerformed(evt);
            }
        });

        jRadioButtonOldClient.setText("Cliente registrado");
        jRadioButtonOldClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOldClientActionPerformed(evt);
            }
        });

        jLabel11.setText("Cliente");

        jTextClientSelected.setEditable(false);

        jPanelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de productos"));

        modelDetal = new javax.swing.table.DefaultTableModel();
        jTableDetal.setModel(modelDetal);
        modelDetal.addColumn("Codigo");
        modelDetal.addColumn("Nomnbre");
        modelDetal.addColumn("Descripcion");
        modelDetal.addColumn("Precio");
        modelDetal.addColumn("Unidad de medida");
        modelDetal.addColumn("Cantidad");
        TableModelListener tml = new TableModelListener(){
            @Override
            public void tableChanged(TableModelEvent e){
                //System.out.println("Hubo un cambio");
                int subtotal=0;
                int price=0;
                int cant=0;
                int IVA=0;
                int total=0;
                for (int i=0;i<modelDetal.getRowCount();i++){
                    price=Integer.parseInt(modelDetal.getValueAt(i,3).toString());
                    cant=Integer.parseInt(modelDetal.getValueAt(i,5).toString());
                    subtotal+= price*cant;
                }
                jTextSubTotal.setText(subtotal+"");
                IVA=subtotal*19/100;
                jTextIVA.setText(IVA+"");
                total=subtotal+IVA;
                jTextTotal.setText(total+"");
            }
        };
        modelDetal.addTableModelListener(tml);
        jScrollPane4.setViewportView(jTableDetal);

        jButtonFrmAddProduct.setText("Agregar productos");
        jButtonFrmAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrmAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDetallesLayout = new javax.swing.GroupLayout(jPanelDetalles);
        jPanelDetalles.setLayout(jPanelDetallesLayout);
        jPanelDetallesLayout.setHorizontalGroup(
            jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFrmAddProduct)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelDetallesLayout.setVerticalGroup(
            jPanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFrmAddProduct)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));

        jCBSearchClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documento", "Nombre y apellido" }));
        jCBSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSearchClientActionPerformed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Primer apellido", "Segundo apellido", "Telefono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClient);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jCBSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jButtonCheckIn.setText("Facturar");
        jButtonCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInActionPerformed(evt);
            }
        });

        jLabel3.setText("Subtotal");

        jLabel8.setText("Total");

        jTextSubTotal.setEditable(false);

        jTextIVA.setEditable(false);

        jTextTotal.setEditable(false);

        jLabel12.setText("I.V.A");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextClientSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButtonNewClient)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButtonOldClient)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonCheckIn)
                                .addGap(95, 95, 95))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(jTextIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelInsertClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNewClient)
                    .addComponent(jRadioButtonOldClient))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextClientSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jPanelInsertClient, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButtonCheckIn)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane5.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venta", new javax.swing.ImageIcon(getClass().getResource("/Images/icono-eficencia.png")), jPanel2); // NOI18N

        jTextNITCC.setEditable(false);

        jTextNameProvider.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Proveedor");

        jLabel4.setText("NIT o C.C");

        jLabel6.setText("Razon Social");

        jButtonFrmAddProvider.setText("Agregar Proveedor");
        jButtonFrmAddProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrmAddProviderActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Lista de productos");

        modelProductIn = new javax.swing.table.DefaultTableModel();
        jTableAddProductIn.setModel(modelProductIn);
        modelProductIn.addColumn("Codigo");
        modelProductIn.addColumn("Nombre");
        modelProductIn.addColumn("Descripcion");
        modelProductIn.addColumn("Unidad de medida");
        modelProductIn.addColumn("Cantidad");
        jScrollPane6.setViewportView(jTableAddProductIn);

        jButtonFrmAddProductIn.setText("Agregar Productos");
        jButtonFrmAddProductIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrmAddProductInActionPerformed(evt);
            }
        });

        jButtonInsertIn.setText("Registrar ingreso");
        jButtonInsertIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextNITCC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNameProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonFrmAddProvider))
                            .addComponent(jLabel7)
                            .addComponent(jButtonFrmAddProductIn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInsertIn)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFrmAddProvider)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNameProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNITCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(jButtonFrmAddProductIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonInsertIn)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingreso de productos", new javax.swing.ImageIcon(getClass().getResource("/Images/WEB-FCH-FINAL-PARA-MARIO-40 (1).png")), jPanel3); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Caja menor");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Monto");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Motivo");

        jTextCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextReason.setColumns(20);
        jTextReason.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextReason.setRows(5);
        jScrollPane3.setViewportView(jTextReason);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boton-guardar-png-4.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCash, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Caja menor", new javax.swing.ImageIcon(getClass().getResource("/Images/caja-registradora-006.png")), jPanel4); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jButton2.setText("Cerrar sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/changePass.png"))); // NOI18N
        jButton3.setText("Cambiar contraseña");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel19.setVisible(false);
        jLabel19.setText("Contraseña antigua");

        jLabel20.setVisible(false);
        jLabel20.setText("Nueva contraseña");

        jLabel21.setVisible(false);
        jLabel21.setText("Confirmar contraseña");

        jPasswordOld.setVisible(false);
        jPasswordOld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordOldKeyTyped(evt);
            }
        });

        jPasswordNew.setVisible(false);

        jPasswordConfirm.setVisible(false);

        jButtonSaveChangePass.setVisible(false);
        jButtonSaveChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boton-guardar-png-4.png"))); // NOI18N
        jButtonSaveChangePass.setText("Guardar");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Contraseña incorrecta");
        jLabel22.setVisible(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 102));
        jLabel23.setText("Contraseña correcta");
        jLabel23.setVisible(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton2)
                        .addGap(79, 79, 79)
                        .addComponent(jButton3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordOld)
                                    .addComponent(jPasswordNew)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23)))))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSaveChangePass)
                .addGap(220, 220, 220))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jPasswordOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jPasswordNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButtonSaveChangePass)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuenta de usuario", new javax.swing.ImageIcon(getClass().getResource("/Images/585e4bcdcb11b227491c3396 (2).png")), jPanel7); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static JTable getjTableDetal() {
        return jTableDetal;
    }

    private boolean checkMail(String mail) {
        String emailPattern = "^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@"
                + "[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4})$";
        Pattern pattern = Pattern.compile(emailPattern);
        String email = mail;
        boolean valide = false;
        if (mail != null) {
            Matcher matcher = pattern.matcher(email);
            if (matcher.matches()) {
                valide = true;
            }
        }
        return valide;
    }

    private void jbtSearchProFrmUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchProFrmUserActionPerformed
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();

        jTable2.setModel(model);
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Precio");
        model.addColumn("Unidad de medida");
        model.addColumn("Cantidad");
        QueryProduct qpw = new QueryProduct();
        ResultSet rsw = null;
        if (!jTextSearchProFrmUser.getText().equals("")) {
            rsw = qpw.getProductForWhere(jCbSearchProFrmUser.getSelectedItem().toString(), jTextSearchProFrmUser.getText());
            int size = qpw.getCantProduct();
            try {
                while (rsw.next()) {
                    Object[] rowModel = new Object[size];
                    for (int i = 0; i < size; i++) {
                        rowModel[i] = rsw.getObject(i + 1);
                    }
                    model.addRow(rowModel);
                }
            } catch (SQLException e) {
                System.err.print(e);
            }
        } else {
            if (jTextSearchProFrmUser.getText().equals("")) {
                try {
                    java.sql.ResultSet rsp = qpw.getProducts();
                    int quantityRow = qpw.getCantProduct();
                    while (rsp.next()) {
                        Object[] rowModel = new Object[quantityRow];
                        for (int i = 0; i < quantityRow; i++) {
                            rowModel[i] = rsp.getObject(i + 1);
                        }
                        model.addRow(rowModel);
                    }
                } catch (SQLException e) {
                    System.err.print(e);
                }

            }
        }

        qpw.closeConnection();
    }//GEN-LAST:event_jbtSearchProFrmUserActionPerformed

    private void jbtnInsertClientejbtnInsertClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertClientejbtnInsertClienteActionPerformed
        QueryClient qp = new QueryClient();
        Client client = new Client();
        if (!jTextIdClient.getText().equals("") && !jTextNameClient.getText().equals("") && !jTextFLastName.getText().equals("")) {
            if (!jTextEmailClient.getText().equals("")) {
                boolean aux = checkMail(jTextEmailClient.getText());
                if (aux) {
                    client.setDocument(jTextIdClient.getText());
                    client.setName(jTextNameClient.getText());
                    client.setFirstLastName(jTextFLastName.getText());
                    client.setLastLastName(jTextLLastName.getText());
                    client.setPhone(jTextPhoneClient.getText());
                    client.setEmail(jTextEmailClient.getText());

                    if (qp.insertClient(client)) {
                        JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");
                        jTextClientSelected.setText(jTextIdClient.getText());
                        jTextIdClient.setText("");
                        jTextNameClient.setText("");
                        jTextFLastName.setText("");
                        jTextLLastName.setText("");
                        jTextPhoneClient.setText("");
                        jTextEmailClient.setText("");
                        jPanelInsertClient.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas al registrar el cliente");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Correo invalido");
                }
            } else {
                if (jTextEmailClient.getText().equals("")) {
                    client.setDocument(jTextIdClient.getText());
                    client.setName(jTextNameClient.getText());
                    client.setFirstLastName(jTextFLastName.getText());
                    client.setLastLastName(jTextLLastName.getText());
                    client.setPhone(jTextPhoneClient.getText());
                    client.setEmail(jTextEmailClient.getText());

                    if (qp.insertClient(client)) {
                        JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");
                        jTextClientSelected.setText(jTextIdClient.getText());
                        jTextIdClient.setText("");
                        jTextNameClient.setText("");
                        jTextFLastName.setText("");
                        jTextLLastName.setText("");
                        jTextPhoneClient.setText("");
                        jTextEmailClient.setText("");
                        jPanelInsertClient.setVisible(false);

                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas al registrar el cliente");
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Campos requeridos se enuentran vacios");
        }
    }//GEN-LAST:event_jbtnInsertClientejbtnInsertClienteActionPerformed

    private void jRadioButtonNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNewClientActionPerformed
        this.jPanelInsertClient.setVisible(true);
        this.jPanel6.setVisible(false);
    }//GEN-LAST:event_jRadioButtonNewClientActionPerformed

    private void jRadioButtonOldClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOldClientActionPerformed
        this.jPanelInsertClient.setVisible(false);
        this.jPanel6.setVisible(true);
    }//GEN-LAST:event_jRadioButtonOldClientActionPerformed

    private void jButtonFrmAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrmAddProductActionPerformed
        frmAddProduct.setVisible(true);
    }//GEN-LAST:event_jButtonFrmAddProductActionPerformed

    private void jCBSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSearchClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSearchClientActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        TableModel model = new TableModel();
        jTableClient.setModel(model);
        model.addColumn("Documento");
        model.addColumn("Nombre");
        model.addColumn("Primer apellido");
        model.addColumn("Segundo apellido");
        model.addColumn("Telefono");
        model.addColumn("Correo");
        String aux = jCBSearchClient.getSelectedItem().toString();
        String attribute = new String(aux);
        QueryClient qc = new QueryClient();
        try {
            java.sql.ResultSet rsc = qc.getClientForWhere(attribute, jTextField5.getText());
            int quantityRow = qc.getCantClient();
            while (rsc.next()) {
                Object[] rowModel = new Object[quantityRow];
                for (int i = 0; i < quantityRow; i++) {
                    rowModel[i] = rsc.getObject(i + 1);
                }
                //jCBSearchClient.get
                model.addRow(rowModel);
            }
        } catch (SQLException e) {
            System.err.print(e);
        }
        qc.closeConnection();
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientMouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTableClient.getSelectedRow();
            jTextClientSelected.setText(jTableClient.getValueAt(row, 0).toString());
            jPanel6.setVisible(false);
        }
    }//GEN-LAST:event_jTableClientMouseClicked

    private void jButtonCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInActionPerformed
        QueryBill Qbill = new QueryBill();
        Bill bill = new Bill();
        int j = 0;
        bill.setClient(this.jTextClientSelected.getText());
        bill.setUser(user);
        bill.setSubtotal(Integer.parseInt(jTextSubTotal.getText()));
        bill.setIva(Integer.parseInt(jTextIVA.getText()));
        bill.setTotal(Integer.parseInt(jTextTotal.getText()));
        if (Qbill.insertBill(bill)) {
            int row = this.modelDetal.getRowCount();
            String[] elementId = new String[row];
            int[] elementCant = new int[row];
            String auxId = new String();
            int auxCant = 0;
            for (int i = 0; i < row; i++) {
                //Problema no se de donde
                auxId = modelDetal.getValueAt(i, 0).toString();
                auxCant = Integer.parseInt(modelDetal.getValueAt(i, 5).toString());
                elementId[i] = auxId;
                elementCant[i] = auxCant;
            }

            ResultSet lastBill = null;
            BillProduct bp = new BillProduct();
            lastBill = Qbill.getLastIdBill();
            try {
                while (lastBill.next()) {
                    bp.setNBill(lastBill.getInt(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(HomeUser.class.getName()).log(Level.SEVERE, null, ex);
            }

            QueryBillProduct qbp = new QueryBillProduct();

            for (j = 0; j < row; j++) {
                bp.setIdProduct(elementId[j]);
                bp.setCant(elementCant[j]);
                qbp.insertBillProduc(bp);
            }
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable(this);
            boolean top = pj.printDialog();
            if (top) {
                try {
                    pj.print();
                } catch (PrinterException ex) {
                    Logger.getLogger(HomeUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            JOptionPane.showMessageDialog(this, "Factura registrada correctamente");
        }
    }//GEN-LAST:event_jButtonCheckInActionPerformed

    private void jButtonFrmAddProductInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrmAddProductInActionPerformed
        AddProductIn frmAddProduct = new AddProductIn(this, true);
        frmAddProduct.setVisible(true);
    }//GEN-LAST:event_jButtonFrmAddProductInActionPerformed

    private void jButtonFrmAddProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrmAddProviderActionPerformed
        AddProvider frmAddProvider = new AddProvider(this, true);
        frmAddProvider.setVisible(true);
    }//GEN-LAST:event_jButtonFrmAddProviderActionPerformed

    private void jButtonInsertInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertInActionPerformed
        QueryProviderProduct qpp = new QueryProviderProduct();
        QueryCheckInProduct qcip = new QueryCheckInProduct();
        QueryUser qu = new QueryUser();
        ProviderProduct pp = new ProviderProduct();
        CheckInProduct cip = new CheckInProduct();
        int cantProduct = 0;
        String documentUser = qu.getUserForNick(user);
        if (!jTextNITCC.getText().equals("") && (modelProductIn.getRowCount()) > 0) {
            cip.setProvider(jTextNITCC.getText());
            cip.setUser(documentUser);
            if (qcip.insertCheckInProduct(cip)) {
                cantProduct = modelProductIn.getRowCount();
                int i = 0;
                String lastCheckInProduct = qcip.lastCheckInProduct();
                pp.setCheckInProduct(lastCheckInProduct);
                for (i = 0; i < cantProduct; i++) {
                    pp.setIdProdcut(modelProductIn.getValueAt(i, 0).toString());
                    pp.setCant(Integer.parseInt(modelProductIn.getValueAt(i, 4).toString()));
                    if (!qpp.insertProviderProduct(pp)) {
                        JOptionPane.showMessageDialog(this, "Ocurrió un problema al registrar el ingreso");
                        break;
                    }
                }

                if (i == cantProduct) {
                    JOptionPane.showMessageDialog(this, "Ingreso de productos registrado exitosamente");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Campos requeridos se encuentran vacios");
        }
    }//GEN-LAST:event_jButtonInsertInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QueryPettyCash qpc = new QueryPettyCash();
        QueryUser qu = new QueryUser();
        PettyCash pc = new PettyCash();
        pc.setCash(Integer.parseInt(jTextCash.getText()));
        pc.setReason(jTextReason.getText());
        pc.setUser(qu.getUserForNick(user));
        if(qpc.insertPettyCash(pc)){
            JOptionPane.showMessageDialog(this, "Registrado exitosamente");
        }
        else{
            JOptionPane.showMessageDialog(this, "Problemas en el registro");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jLabel19.setVisible(true);
       jLabel20.setVisible(true);
       jLabel21.setVisible(true);
       jPasswordOld.setVisible(true);
       jPasswordNew.setVisible(true);
       jPasswordConfirm.setVisible(true);
       jButtonSaveChangePass.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordOldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordOldKeyTyped
        QueryUser qucp = new QueryUser();
        String passOld = new String(jPasswordOld.getPassword()); 
        if(qucp.getOldPassword(DigestUtils.sha1Hex(passOld))){
            jLabel23.setVisible(true);
            jLabel22.setVisible(false);
        }
        else{
            jLabel22.setVisible(true);
            jLabel23.setVisible(false);
        }
    }//GEN-LAST:event_jPasswordOldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCheckIn;
    private javax.swing.JButton jButtonFrmAddProduct;
    private javax.swing.JButton jButtonFrmAddProductIn;
    private javax.swing.JButton jButtonFrmAddProvider;
    private javax.swing.JButton jButtonInsertIn;
    private javax.swing.JButton jButtonSaveChangePass;
    private javax.swing.JComboBox<String> jCBSearchClient;
    private javax.swing.JComboBox<String> jCbSearchProFrmUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelInsertClient;
    private javax.swing.JPasswordField jPasswordConfirm;
    private javax.swing.JPasswordField jPasswordNew;
    private javax.swing.JPasswordField jPasswordOld;
    private javax.swing.JRadioButton jRadioButtonNewClient;
    private javax.swing.JRadioButton jRadioButtonOldClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private static javax.swing.JTable jTableAddProductIn;
    private javax.swing.JTable jTableClient;
    private static javax.swing.JTable jTableDetal;
    private javax.swing.JTextField jTextCash;
    private javax.swing.JTextField jTextClientSelected;
    private javax.swing.JTextField jTextEmailClient;
    private javax.swing.JTextField jTextFLastName;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextIVA;
    private javax.swing.JTextField jTextIdClient;
    private javax.swing.JTextField jTextLLastName;
    private static javax.swing.JTextField jTextNITCC;
    private javax.swing.JTextField jTextNameClient;
    private static javax.swing.JTextField jTextNameProvider;
    private javax.swing.JTextField jTextPhoneClient;
    private javax.swing.JTextArea jTextReason;
    private javax.swing.JTextField jTextSearchProFrmUser;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JButton jbtSearchProFrmUser;
    private javax.swing.JButton jbtnInsertCliente;
    // End of variables declaration//GEN-END:variables
}
